import { useState } from 'react';
import Link from 'next/link';
import type { Recording, Sample } from '../lib/record';
import { labelLayer, labelRole, semanticKey } from '../lib/record';
import type { Lens, LensRecord, HeadRow, Prediction } from '../lib/lenses';
import { compatibleReadout, distributionDelta, headKey, vocabularyAt, lensAvailability } from '../lib/lenses';

const n = (v?: number) => v === undefined ? '—' : v.toPrecision(4);
const pct = (v?: number) => v === undefined ? 'not retained' : `${(v * 100).toFixed(2)}%`;
export function Missing({ children }: { children: React.ReactNode }) { return <div className="lens-missing"><span className="eyebrow">EVIDENCE UNAVAILABLE</span><p>{children}</p></div>; }
export function VocabularyBars({ rows, limit = 10 }: { rows: Prediction[]; limit?: number }) {
  return <div className="lens-bars">{rows.slice(0, limit).map(p => <div key={p.token_id}><span>{p.token}<small>#{p.rank} · id {p.token_id}</small></span><i><b style={{ width: `${p.probability * 100}%` }} /></i><strong>{pct(p.probability)}</strong></div>)}</div>;
}
export function ResearchView({ record, samples, selected, position, role, lenses, lens, setLens, selectedHead, setHead, select, load, save, loadTarget, target, targetSamples, targetLenses, loadTargetAnalysis, fullAnalysis }: {
  record: Recording; samples: Sample[]; selected?: Sample; position: number; role: Sample['role'];
  fullAnalysis?: LensRecord; lenses?: LensRecord; lens: Lens; setLens: (lens: Lens) => void; selectedHead?: string;
  setHead: (head: string) => void; select: (sample: Sample) => void; load: () => void; save: () => void;
  loadTarget: () => void; target?: Recording; targetSamples: Sample[]; targetLenses?: LensRecord; loadTargetAnalysis: () => void;
}) {
  const availability = lensAvailability(fullAnalysis);
  const noHeadCapture = !availability.Heads;
  const [vocabMetric, setVocabMetric] = useState<'probability' | 'rank' | 'logit' | 'logprob'>('probability');
  const [tracked, setTracked] = useState('');
  const [topK, setTopK] = useState(10);
  const [compareKey, setCompareKey] = useState('');
  const [compareRun, setCompareRun] = useState(false);
  const [headTarget, setHeadTarget] = useState('');
  const [experimentId, setExperimentId] = useState('');
  const row = vocabularyAt(lenses, selected);
  const trajectory = samples.filter(s => s.position === position && s.role === role).flatMap(sample => {
    const row = vocabularyAt(lenses, sample); return row ? [{ sample, row }] : [];
  });
  const targets = [...new Set(trajectory.flatMap(r => r.row.targets.map(t => t.token)))];
  const token = targets.includes(tracked) ? tracked : targets[0];
  const sampleByKey = new Map(samples.map(s => [semanticKey(s), s]));
  const possibleHeads = lenses?.heads?.rows.filter(h => sampleByKey.get(h.site)?.position === position) ?? [];
  const headTargets = [...new Set(possibleHeads.map(h => h.target))];
  const targetToken = headTargets.includes(headTarget) ? headTarget : headTargets[0];
  const heads = possibleHeads.filter(h => h.target === targetToken);
  const hot = [...heads].sort((a, b) => Math.abs(b.dla) - Math.abs(a.dla));
  const head = heads.find(h => headKey(h) === selectedHead && h.site === (selected && semanticKey(selected)));
  const chooseHead = (h: HeadRow) => { const s = sampleByKey.get(h.site); if (s) { select(s); setHead(headKey(h)); setLens('Content'); } };
  const headIds = [...new Set(heads.map(h => h.head))].sort((a, b) => a - b);
  const layers = [...new Set(heads.map(h => sampleByKey.get(h.site)!.layer))].sort((a,b) => a-b);
  const headByCell = new Map(heads.map(h => [`${sampleByKey.get(h.site)!.layer}:${h.head}`, h]));
  const maxDla = Math.max(...heads.map(h => Math.abs(h.dla)), 0);
  const content = head?.content;
  const candidates = (compareRun ? targetSamples : samples).filter(s => s.position === position);
  const counterpart = candidates.find(s => semanticKey(s) === compareKey) ?? (compareRun ? candidates.find(s => selected && semanticKey(s) === semanticKey(selected)) : candidates.find(s => selected && semanticKey(s) !== semanticKey(selected)));
  const otherRow = vocabularyAt(compareRun ? targetLenses : lenses, counterpart);
  const experiments = lenses?.experiments?.filter(e => selected && e.site === semanticKey(selected) && (!head || e.head === head.head)) ?? [];
  const experiment = experiments.find(e => e.fork === experimentId) ?? experiments[0];
  const headCaptureMissing = <Missing>This recording contains no individual attention-head observations. Standard capture records aggregate attention and FFN writes; it cannot reconstruct a DLA heatmap, source-token attention maps, or head content projections.<span className="capture-actions"><button className="text-action" onClick={()=>setLens('Logits')}>Inspect captured logits →</button>{!record.vindex3 && <button className="text-action" onClick={load}>Import matching head analysis →</button>}<Link href="/demo/heads" target="_blank" rel="noreferrer">Open synthetic head demo ↗</Link></span><span className="capture-detail">Real Granite heads require a new canonical capture with the separate per-head observer. The demo opens another recording and does not add evidence to this run.</span></Missing>;
  return <section className="research-view">
    <div className="field-caption"><div><p className="eyebrow">ONE SELECTION / DIFFERENT QUESTIONS</p><h2>{noHeadCapture && (lens === 'Heads' || lens === 'Content') ? 'Per-head capture is missing.' : ({ Logits: 'When does the answer emerge?', Heads: 'Which heads write toward it?', Content: 'What does this head write?', Compare: 'What changed between states?', 'KV anatomy': 'The cost of carrying context.', Experiment: 'Does the explanation survive?' })[lens]}</h2></div></div>
    <div className="lens-tabs" aria-label="Analysis lens">{(['Logits', 'Heads', 'Content', 'Compare', 'KV anatomy', 'Experiment'] as Lens[]).map(l => <button key={l} aria-pressed={lens === l} onClick={() => setLens(l)} data-unavailable={!availability[l] || undefined}>{l}{!availability[l] && <small>Not captured</small>}</button>)}</div>
    <div className="lens-subject"><span>Position {position} · {record.tokens[position]} · {selected ? `${labelLayer(selected.layer)} / ${labelRole(selected.role)}` : 'select a site'}{head ? ` · H${head.head}` : ''}</span>{!record.vindex3 && <button onClick={load}>Open analysis ↗</button>}{lenses && <button onClick={save}>Save analysis ↓</button>}</div>
    <p className="lens-evidence">{lenses ? `${lenses.provenance === 'synthetic' ? 'SYNTHETIC ANALYSIS / authored walkthrough' : 'RUNNER-DECLARED ANALYSIS / derived from captured evidence'} · ${lenses.provider}` : 'No analysis sidecar attached. Standard raw probes remain available in the inspector.'}</p>
    {record.provenance === 'executor' && noHeadCapture && <p className="capture-summary">This record: aggregate carrier / attention / FFN writes{availability.Logits ? ' + normalized vocabulary' : ''}. Individual heads, head content, and source-token attention are not captured.</p>}
    {lens === 'Logits' && <>
      {trajectory.length ? <><div className="lens-controls"><label>Track <select value={token} onChange={e => setTracked(e.target.value)}>{targets.map(t => <option key={t}>{t}</option>)}</select></label><label>Metric <select value={vocabMetric} onChange={e => setVocabMetric(e.target.value as typeof vocabMetric)}><option value="probability">Probability</option><option value="rank">Rank</option><option value={lenses?.vocabulary?.value_kind === 'logprob' ? "logprob" : "logit"}>{lenses?.vocabulary?.value_kind === 'logprob' ? "Log probability" : "Logit"}</option></select></label><label>Top <select value={topK} onChange={e => setTopK(Number(e.target.value))}>{[5,10,20].map(k => <option key={k}>{k}</option>)}</select></label></div>
      <p className="lens-note">Readout: {lenses?.vocabulary?.method} · basis: {lenses?.vocabulary?.basis}. {lenses?.vocabulary?.value_kind === 'logprob' ? 'Probability = exp(recorded log-probability). Raw logits and entropy are not recorded.' : 'Entropy uses the full vocabulary.'} Retained top tokens are not re-normalized.</p>
      <div className="lens-columns"><div className="lens-scroll"><table className="lens-table"><caption>Token emergence / {token}</caption><thead><tr><th>Site</th><th>Top token</th><th>{vocabMetric}</th><th>Entropy (nats)</th></tr></thead><tbody>{trajectory.map(({ sample, row }) => { const t = row.targets.find(p => p.token === token); return <tr key={row.site} data-selected={selected && semanticKey(selected) === row.site}><th><button onClick={() => select(sample)}>{labelLayer(sample.layer)} →</button></th><td>{row.top[0]?.token ?? '—'}</td><td>{t ? vocabMetric === 'probability' ? pct(t.probability) : n(t[vocabMetric]) : '—'}</td><td>{n(row.entropy)}</td></tr>; })}</tbody></table></div><div><h3>Selected state / vocabulary</h3>{row ? <VocabularyBars rows={row.top} limit={topK} /> : <Missing>No vocabulary readout at this selected boundary.</Missing>}{availability.Heads ? <button className="text-action" onClick={() => setLens('Heads')}>Follow the head contributions →</button> : <p className="lens-note">Individual head contributions are not captured in this recording.</p>}</div></div></> : <Missing>Normalized vocabulary readout has not been captured at this position and boundary. A full output-head readout with its normalization, scaling and soft-capping method is required. Raw head-row probes do not provide probabilities, ranks or entropy.</Missing>}
    </>}
    {lens === 'Heads' && <>{noHeadCapture ? headCaptureMissing : heads.length ? <><div className="lens-controls"><label>DLA target <select value={targetToken} onChange={e => setHeadTarget(e.target.value)}>{headTargets.map(t => <option key={t}>{t}</option>)}</select></label></div><p className="lens-note">{lenses?.heads?.method} · {lenses?.heads?.basis}. Direct attribution is not causal effect. + supports / − opposes / — unavailable. Absolute scale: {n(maxDla)}. {headIds.length} heads × {layers.length} captured layers at this position.</p><div className="lens-columns"><div className="lens-scroll"><table className="head-heatmap"><caption>Layer × head / signed token-direction attribution</caption><thead><tr><th>Layer</th>{headIds.map(h => <th key={h}>H{h}</th>)}</tr></thead><tbody>{layers.map(l => <tr key={l}><th>{labelLayer(l)}</th>{headIds.map(id => { const h = headByCell.get(`${l}:${id}`); return <td key={id}><button disabled={!h} aria-pressed={!!h && headKey(h) === selectedHead} title={h ? `${labelLayer(l)} H${id}: ${h.dla}` : 'Not captured'} onClick={() => h && chooseHead(h)} style={{ backgroundColor: h ? `rgba(${h.dla < 0 ? '196,153,125' : '178,201,156'},${.05 + (maxDla ? Math.abs(h.dla) / maxDla : 0) * .65})` : undefined }}>{h ? `${h.dla >= 0 ? '+' : '−'}${Math.abs(h.dla).toFixed(2)}` : '—'}</button></td>; })}</tr>)}</tbody></table></div><div className="hot-heads"><h3>Strongest recorded heads</h3><p className="lens-note">Ranked by absolute DLA at this position.</p>{hot.slice(0, 12).map((h, i) => <button key={headKey(h)} onClick={() => chooseHead(h)}><small>{i+1}</small><span>{labelLayer(sampleByKey.get(h.site)!.layer)} / H{h.head}</span><b>{n(h.dla)}</b></button>)}</div></div></> : <Missing>Head analysis is attached, but no head rows are available for this position at the current replay cursor. Select a captured position or advance replay.</Missing>}</>}
    {lens === 'Content' && <>{noHeadCapture ? headCaptureMissing : head ? <><div className="lens-controls"><strong>{labelLayer(selected!.layer)} / H{head.head}</strong><button onClick={() => setLens('Heads')}>← Choose another head</button></div><div className="lens-columns"><div><h3>Token directions</h3>{content ? <><p className="lens-note">{content.method} · {content.basis} · vector norm {n(content.vector_norm)}</p><div className="lens-bars">{[...content.projections].sort((a,b) => Math.abs(b.coefficient)-Math.abs(a.coefficient)).map(p => <div key={p.token_id}><span>{p.token}</span><i><b className={p.coefficient < 0 ? 'negative' : ''} style={{ width: `${Math.abs(p.coefficient) / (Math.max(...content.projections.map(p => Math.abs(p.coefficient))) || 1) * 100}%` }} /></i><strong>{p.coefficient > 0 ? '+' : ''}{n(p.coefficient)}</strong></div>)}</div></> : <Missing>No content projection for this head.</Missing>}
    <h3>Source positions / attention weights</h3><div className="lens-bars">{[...head.sources].sort((a,b)=>b.weight-a.weight).map(s => <div key={s.position}><span>{record.tokens[s.position]}<small>position {s.position}</small></span><i><b style={{ width: `${s.weight * 100}%` }} /></i><strong>{pct(s.weight)}</strong></div>)}</div><p className="lens-note">Retained source mass: {pct(head.sources.reduce((sum,s)=>sum+s.weight,0))}. Weights are not causal contribution.</p></div><div><h3>Signal dimensionality</h3>{content?.dimensionality ? <><div className="signal-thresholds">{(['d95','d99','d999'] as const).map((d,i) => <div key={d}><span>{['95%','99%','99.9%'][i]}</span><strong>{content.dimensionality![d]}</strong><small>directions</small></div>)}</div><p className="lens-note">{content.dimensionality.method} / {content.dimensionality.dimensions} dimensions. Thresholds describe this declared signal, not all factual knowledge.</p></> : <Missing>No dimensionality analysis.</Missing>}
    <h3>Orthogonality diagnostic</h3>{content?.orthogonality ? <><p className="lens-note">{content.orthogonality.method}</p><dl className="lens-facts">{content.orthogonality.pairs.map((p,i) => <div key={i}><dt>{p.label}</dt><dd>{n(p.cosine)}</dd></div>)}</dl><p className="lens-note">Cosine alone does not establish independence or causal sufficiency.</p></> : <Missing>No orthogonality diagnostic.</Missing>}<button className="text-action" onClick={() => setLens('Experiment')}>Inspect intervention evidence →</button><button className="text-action" onClick={() => setLens('KV anatomy')}>Inspect KV anatomy →</button></div></div></> : <Missing>{heads.length ? 'Select a captured attention head in the DLA heatmap. This will also select its attention write.' : 'No captured heads are visible at this position and replay cursor.'} <button className="text-action" onClick={() => setLens('Heads')}>Open heads →</button></Missing>}</>}
    {lens === 'Compare' && <><div className="lens-controls"><label>Compare with <select value={compareRun ? 'run' : 'depth'} onChange={e => { setCompareRun(e.target.value === 'run'); setCompareKey(''); }}><option value="depth">Another boundary</option><option value="run" disabled={!target}>Another recording</option></select></label><button onClick={loadTarget}>Open comparison run ↗</button>{target && !target.vindex3 && <button onClick={loadTargetAnalysis}>Open target analysis ↗</button>}<label>Target site <select value={counterpart ? semanticKey(counterpart) : ''} onChange={e => setCompareKey(e.target.value)}>{candidates.map(s => <option key={semanticKey(s)} value={semanticKey(s)}>{labelLayer(s.layer)} · {labelRole(s.role)}</option>)}</select></label></div>
    <p className="lens-note">Position {position} / {compareRun ? `${record.tokens[position]} ↔ ${target?.tokens[position] ?? 'unavailable'}. Alignment is positional and by semantic site; token meanings are not assumed equal.` : 'Same recorded token at two boundaries.'} Write magnitudes are not additive attribution.</p>
    {selected && counterpart ? <><table className="lens-table"><caption>{record.id}{compareRun ? ` ↔ ${target?.id}` : ''}</caption><thead><tr><th>Measurement</th><th>{labelLayer(selected.layer)} / {labelRole(selected.role)}</th><th>{labelLayer(counterpart.layer)} / {labelRole(counterpart.role)}</th><th>Δ target − base</th></tr></thead><tbody>{(['norm','delta'] as const).map(m => <tr key={m}><th>{m === 'norm' ? 'Carrier L2' : 'Applied-write L2'}</th><td>{n(selected[m])}</td><td>{n(counterpart[m])}</td><td>{n(counterpart[m]-selected[m])}</td></tr>)}{record.answers.map(a => <tr key={a}><th>{a} / raw readout</th><td>{n(selected.logits[a])}</td><td>{n(counterpart.logits[a])}</td><td>{selected.logits[a] !== undefined && counterpart.logits[a] !== undefined && (!compareRun || (target && compatibleReadout(record, target))) ? n(counterpart.logits[a]-selected.logits[a]) : 'incompatible / unavailable'}</td></tr>)}</tbody></table><div className="lens-columns"><div><h3>Base vocabulary</h3>{row ? <VocabularyBars rows={row.top} /> : <Missing>No normalized vocabulary at the base state.</Missing>}</div><div><h3>Target vocabulary</h3>{compareRun && targetLenses?.vocabulary && <p className="lens-note">{targetLenses.provenance} · {targetLenses.vocabulary.method} · {targetLenses.vocabulary.basis}</p>}{otherRow ? <VocabularyBars rows={otherRow.top} /> : <Missing>{compareRun ? 'The comparison record has no attached analysis sidecar.' : 'No normalized vocabulary at the target state.'}</Missing>}</div></div></> : <Missing>Select two recorded boundaries at this position.</Missing>}</>}
    {lens === 'KV anatomy' && <>{lenses?.kv ? <><p className="lens-note">{lenses.kv.method} · accounting at event {lenses.kv.sequence}</p><div className="kv-total"><strong>{lenses.kv.total_bytes.toLocaleString()}</strong><span>bytes / total retained KV</span></div><div className="kv-track"><i style={{ width: `${lenses.kv.key_bytes/lenses.kv.total_bytes*100}%` }} /><b style={{ width: `${lenses.kv.value_bytes/lenses.kv.total_bytes*100}%` }} /></div><div className="lens-controls"><span>K / {lenses.kv.key_bytes.toLocaleString()} B</span><span>V / {lenses.kv.value_bytes.toLocaleString()} B</span></div>{lenses.kv.content ? <><h3>Task-scoped content representation</h3><p className="lens-note">{lenses.kv.content.scope} · {lenses.kv.content.method}</p><div className="kv-content"><strong>{lenses.kv.content.bytes.toLocaleString()} B</strong><span>{(lenses.kv.total_bytes/lenses.kv.content.bytes).toLocaleString(undefined,{maximumFractionDigits:1})} : 1 total KV : content</span></div><p className="lens-note">Content is {((lenses.kv.content.bytes/lenses.kv.total_bytes)*100).toPrecision(4)}% of total bytes. This compares two representations; it does not identify a removable slice of the cache or prove replacement parity.</p><p className="lens-method">Supporting witness / {lenses.kv.content.witness}</p></> : <Missing>No supported content-size estimate. KV bytes alone do not establish a factual-content ratio.</Missing>}</> : <Missing>KV accounting has not been supplied at the current replay cursor. Standard carrier stats do not measure cache allocation or factual-content size.</Missing>}</>}
    {lens === 'Experiment' && <>{experiment ? <><div className="lens-controls"><label>Recorded intervention <select value={experiment.fork} onChange={e => setExperimentId(e.target.value)}>{experiments.map(e => <option key={e.fork} value={e.fork}>{e.kind} / H{e.head} / {e.fork}</option>)}</select></label></div><p className="lens-note">{experiment.method} · target {experiment.target}</p><div className="experiment-path"><span>BASE<small>{experiment.parent}</small></span><b>→ {experiment.kind} H{experiment.head} →</b><span>FORK<small>{experiment.fork}</small></span></div><table className="lens-table"><thead><tr><th>Token</th><th>Before</th><th>After</th><th>Δ probability</th></tr></thead><tbody>{distributionDelta(experiment.before, experiment.after).map(p => <tr key={p.id}><th>{p.token}</th><td>{pct(p.before)}</td><td>{pct(p.after)}</td><td>{p.delta === undefined ? 'unavailable' : `${(p.delta*100).toFixed(2)} pp`}</td></tr>)}</tbody></table><p className="lens-note">{experiment.kl ? `KL(before ∥ after) / full vocabulary: ${n(experiment.kl.nats)} nats.` : 'Full-vocabulary KL unavailable. Truncated top-k cannot establish it.'}</p><p className="lens-method">Witness / {experiment.witness}</p><p className="lens-note">Recorded experiment evidence. This view does not execute a new intervention or mutate the parent.</p></> : <Missing>No intervention record for this selected site{head ? ` / H${head.head}` : ''}. Ablation, patching and injection require a separate canonical fork and its evidence. The hosted UI currently has no intervention runner.</Missing>}</>}
    {lenses && <details className="lens-provenance"><summary>Analysis identity / methods</summary><p>Source SHA-256 / {lenses.source_sha256}</p><p>Run / {lenses.run_id}</p><p>Source binding verifies record identity, not the scientific validity of the provider’s analysis.</p>{lenses.readout_witness && <p>Exporter readout check: PASS at {lenses.readout_witness.positions} positions. {lenses.readout_witness.criterion}. Canonical / readout logits SHA-256: {lenses.readout_witness.canonical_logits_sha256}</p>}</details>}
  </section>;
}
